version: '3.1'
services:
   mysql:
      restart: always
      image: mysql:5.7
      container_name: my_mysql
      volumes:
         - ./mydir:/mydir
         - ./datadir:/var/lib/mysql
         - ./conf/my.cnf:/etc/my.cnf
         #      数据库还原目录 可将需要还原的sql文件放在这里
         - ./docker/mysql/source:/docker-entrypoint-initdb.d
      environment:
         - "MYSQL_ROOT_PASSWORD=asd280qwe"
         - "MYSQL_DATABASE=management"
         - "TZ=Asia/Shanghai"
      ports:
         - 3306:3306