FROM node:latest as bangdai-vue

MAINTAINER mmq

RUN true \
    && npm config set registry https://registry.npm.taobao.org \
    && npm install -g @vue/cli@3 latest 

RUN mkdir /bangdai-vue

WORKDIR /bangdai-vue

RUN chmod +x /bangdai-vue

# 拷贝前端项目到bangdai目录下
COPY ./bangdai-vue .

RUN ls

RUN npm install

RUN npm run build:prod


FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf

COPY ./nginx/nginx.conf /etc/nginx/

# 拷贝前端vue项目打包后生成的文件到nginx下运行
COPY --from=bangdai-vue /bangdai-vue/dist /usr/share/nginx/html

EXPOSE 80

MAINTAINER mmq

# 使用daemon off的方式将nginx运行在前台保证镜像不至于退出
CMD ["nginx", "-g", "daemon off;"]
