version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asd280qwe
    ports:
      - 27017:27017
    # 数据持久化
    volumes:
      - ./home/mongotest:/data/db